version: "3"

tasks:
  setup:
    desc: Install dependencies and set up the environment
    cmds:
      - pnpm install --frozen-lockfile
    silent: true
  dev:
    desc: Install dependencies and set up the environment
    cmds:
      - pnpm dev
    silent: true
