# This is a configuration file for MegaLinter, a code quality tool.
CONSOLE_REPORTER: true
CONSOLE_REPORTER_SECTIONS: true

CONFIG_REPORTER: true
CONFIG_REPORTER_SUB_FOLDER: IDE-config

GITHUB_COMMENT_REPORTER: true
GITHUB_STATUS_REPORTER: true
CLEAR_REPORT_FOLDER: true

JSON_REPORTER: true
JSON_REPORTER_OUTPUT_DETAIL: detailed

LOG_FILE: mega-linter.log
LOG_LEVEL: INFO

MARKDOWN_SUMMARY_REPORTER: true
MARKDOWN_SUMMARY_REPORTER_FILE_NAME: SUMMARY.md

REPORTERS_MARKDOWN_TYPE: advanced
REPORT_OUTPUT_FOLDER: reports/megalinter

COPYPASTE_JSCPD_CONFIG_FILE: config/.jscpd.json

TAP_REPORTER: true
TAP_REPORTER_SUB_FOLDER: tap

TEXT_REPORTER: true
TEXT_REPORTER_SUB_FOLDER: linters_logs

SPELL_CSPELL_CONFIG_FILE: cspell.config.mjs

IGNORE_GITIGNORED_FILES: true

DISABLE_LINTERS:
  - REPOSITORY_DEVSKIM

EXCLUDED_DIRECTORIES:
  - node_modules
  - .git
  - .idea
  - reports
  - dist
  - logs
  - build
  - coverage
  - .history
  - .cache
  - .next
  - .nuxt
  - .vercel
  - .output
  - venv
  - .venv
  - .history
  - .pytest_cache
  - .mypy_cache
  - .ruff_cache

SHOW_SKIPPED_LINTERS: false
SHOW_ELAPSED_TIME: true
PRINT_ALPACA: true
PRINT_ALL_FILES: true
FLAVOR_SUGGESTIONS: false
FAIL_IF_MISSING_LINTER_IN_FLAVOR: true
DISABLE_ERRORS: false

ERROR_ON_MISSING_EXEC_BIT: true

PYTHON_MYPY_CONFIG_FILE: config/.mypy.ini
ACTION_ACTIONLINT_CONFIG_FILE: .github/actionlint.yaml
ANSIBLE_ANSIBLE_LINT_CONFIG_FILE: config/.ansible-lint
API_SPECTRAL_CONFIG_FILE: config/.spectral.yaml
JAVASCRIPT_PRETTIER_CONFIG_FILE: .prettier.config.mjs
JSON_PRETTIER_CONFIG_FILE: .prettier.config.mjs
TYPESCRIPT_PRETTIER_CONFIG_FILE: .prettier.config.mjs
YAML_PRETTIER_CONFIG_FILE: .prettier.config.mjs
REPOSITORY_KICS_CONFIG_FILE: config/.kics.config.json
ARM_ARM_TTK_CONFIG_FILE: config/.arm-ttk.psd1
LATEX_CHKTEX_CONFIG_FILE: config/.chktexrc
