version: "3"
tasks:
  dev:
    cmds: ["pnpm run dev"]
  build:
    cmds: ["pnpm run build"]
  test:
    cmds: ["pnpm run test"]
  lint:spellcheck:
    cmds: ["pnpm run lint:spellcheck"]
  format:check:
    cmds: ["pnpm run format:check"]
  format:
    cmds: ["pnpm run format"]
