version: "3"

vars:
  ARCH:
    sh: uname -m
  PLATFORM:
    sh: uname -s

tasks:
  lint:
    desc: Run MegaLinter with auto-fix
    cmds: ["pnpm run lint"]

  lint:check:
    desc: Run MegaLinter without auto-fix
    cmds: ["pnpm run lint:check"]

  secrets:
    desc: Scan for secrets using gitleaks
    cmds:
      - gitleaks detect --source . --config=.gitleaks.toml --redact

  lint:spellcheck:
    cmds: ["pnpm run lint:spellcheck"]

  format:check:
    cmds: ["pnpm run format:check"]

  format:
    cmds: ["pnpm run format"]

  lint:copypaste:
    cmds: ["pnpm run lint:copypaste"]

  os:
    cmds:
      - 'echo "Running on {{OS}}/{{ARCH}}"'
    silent: true

  act:sanity:
    desc: Run act with correct container arch for Apple Silicon
    cmds:
      - |
        echo "🧠 Detected: {{OS}}/{{ARCH}}"
        if [[ "{{OS}}" == "darwin" && "{{ARCH}}" == "arm64" ]]; then
          echo "⚙️  Apple Silicon detected — forcing container arch to linux/amd64"
          act push --job sanity-check --container-architecture linux/amd64 --verbose
        else
          act push --job sanity-check --verbose
        fi
    silent: true

  hooks:install:
    desc: Install pre-commit hooks (inside Poetry venv)
    cmds:
      - poetry run pre-commit install
    silent: true

  hooks:run:
    desc: Run all pre-commit hooks on all files (Poetry)
    cmds:
      - poetry run pre-commit run --all-files
    silent: true

  hooks:ci:
    desc: CI-safe pre-commit hook run (Poetry, no install)
    cmds:
      - poetry run pre-commit run --all-files --show-diff-on-failure --color always
    silent: true
