version: "3"
tasks:
  lint:spellcheck:
    cmds: ["pnpm run lint:spellcheck"]
  format:check:
    cmds: ["pnpm run format:check"]
  format:
    cmds: ["pnpm run format"]
  lint:check:
    cmds: ["pnpm run lint:check"]
  lint:copypaste:
    cmds: ["pnpm run lint:copypaste"]
