# Define common labels for Docker objects
x-labels: &labels
  labels:
    app.name: ${COMPOSE_PROJECT_NAME:-universal}

# Shared settings for all services
x-settings: &settings # Restart containers unless stopped manually
  restart: unless-stopped
  # Environment variables for all services
  environment:
    - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME:-universal}
    - APP_NAME=${APP_NAME:-universal}
    - TZ=${TZ:-UTC}
  # Allow access to the host machine from the container
  extra_hosts:
    - "host.docker.internal:host-gateway"
  # Init system for graceful shutdown
  init: true
  # Pull policy for images
  pull_policy: missing
  # Attach the container to the project network
  networks:
    default:
      aliases:
        - ${COMPOSE_PROJECT_NAME:-universal}-network
  # Apply the common labels to all services
  <<: *labels

# Define the Docker network for all services
networks:
  default:
    # Name of the Docker network, based on the project name
    name: ${COMPOSE_PROJECT_NAME:-universal}-network
    # Use the bridge driver for the network (https://docs.docker.com/compose/networking/)
    driver: bridge
    # Allows containers to manually attach to this network
    attachable: true
    # Custom options for bridge network driver
    driver_opts:
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "true"

# Define named volumes for persistent storage
volumes:
  database:
    # Name of the volume for database storage
    name: database
    # Driver for the volume, using local storage
    driver: local
  pgadmin:
    # Name of the volume for database storage
    name: pgadmin
    # Driver for the volume, using local storage
    driver: local
  web:
    # Name of the volume for web server storage
    name: web
    # Driver for the volume, using local storage
    driver: local

# Define the base services in the Docker Compose file
services:
  # API server service
  api:
    container_name: ${API_CONTAINER_NAME:-api}
    hostname: ${API_HOSTNAME:-api}
    build:
      context: .
      dockerfile: ./services/api/Dockerfile
      args:
        - API_PORT=${API_PORT:-8000}
    environment:
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres}
      POSTGRES_DB: ${DATABASE_NAME:-universal}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail http://localhost:${API_PORT:-8000}/health || exit 1",
        ]
      interval: 10s
      timeout: 10s
      retries: 10
    <<: *settings

  # Keycloak / Identity and Access Management Database service
  keycloak-db:
    image: postgis/postgis@sha256:495a314df49c5a7a420ee076042b6f91e30f195a0ce0901d2c2369f5bf67c8e7
    container_name: ${KEYCLOAK_DB_CONTAINER_NAME:-keycloak-db}
    hostname: ${KEYCLOAK_DB_HOSTNAME:-keycloak-db}
    environment:
      POSTGRES_DB: ${KEYCLOAK_DB_NAME:-keycloak}
      POSTGRES_USER: ${KEYCLOAK_DB_USER:-keycloak}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD:-OM3vj4pav6P7Hw5z0JVJoLGmOk8Rit2n}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready --username $KEYCLOAK_DB_USER --dbname $KEYCLOAK_DB_NAME --port $KEYCLOAK_DB_PORT || exit 1",
        ]
      interval: 10s
      timeout: 10s
      retries: 10

  # Keycloak service for Identity and Access Management
  # keycloak:
  #   image: keycloak
  #   container_name: ${KEYCLOAK_CONTAINER_NAME:-keycloak}
  #   hostname: ${KEYCLOAK_HOSTNAME:-keycloak}
  #   environment:

  # PostGIS database service
  database:
    image: postgis/postgis@sha256:495a314df49c5a7a420ee076042b6f91e30f195a0ce0901d2c2369f5bf67c8e7
    container_name: ${DATABASE_CONTAINER_NAME:-database}
    hostname: ${DATABASE_HOSTNAME:-database}
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-universal}
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres}
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready --username $DATABASE_USER --dbname $DATABASE_NAME --port $DATABASE_PORT || exit 1",
        ]
      interval: 10s
      timeout: 10s
      retries: 10
    platform: linux/amd64
    <<: *settings

  # pgAdmin service for managing the PostGIS database
  pgadmin:
    image: dpage/pgadmin4@sha256:6b1c0db09695758c72abcd5160b7c4cc6d0847ab0c90a2403bdbf951f0defb5a
    container_name: ${PGADMIN_CONTAINER_NAME:-pgadmin}
    hostname: ${PGADMIN_HOSTNAME:-pgadmin}
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@universal.localhost}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-adminpassword}
      PGADMIN_CONFIG_ALLOW_SPECIAL_EMAIL_DOMAINS: "['localhost']"
      PGADMIN_LISTEN_PORT: ${PGADMIN_PORT:-5050}
    ports:
      - "${PGADMIN_EXPOSED_PORT:-5050}:${PGADMIN_PORT:-5050}"
    volumes:
      - pgadmin:/var/lib/pgadmin
      - ./services/pgadmin/servers.json:/pgadmin4/servers.json:ro
      - ./services/pgadmin/config_local.py:/pgadmin4/config_local.py:ro
      - ./services/pgadmin/healthcheck.py:/pgadmin4/healthcheck.py:ro
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "python3 /pgadmin4/healthcheck.py"]
      interval: 10s
      timeout: 10s
      retries: 10
    platform: linux/amd64
    <<: *settings

  # Apache2 web server/reverse proxy service
  web:
    container_name: ${WEB_CONTAINER_NAME:-web}
    hostname: ${WEB_HOSTNAME:-web}
    build:
      context: .
      dockerfile: ./services/apache/Dockerfile
    ports:
      - "${WEB_HTTP_EXPOSED_PORT:-80}:${WEB_HTTP_PORT:-80}"
      - "${WEB_HTTPS_EXPOSED_PORT:-443}:${WEB_HTTPS_PORT:-443}"
    volumes:
      - ./services/apache/${APP_ENV}/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
      - ./services/apache/${APP_ENV}/conf/httpd-ssl.conf:/usr/local/apache2/conf/extra/httpd-ssl.conf:ro
      - ./services/apache/${APP_ENV}/certs/cert.key:/usr/local/apache2/conf/server.key:ro
      - ./services/apache/${APP_ENV}/certs/cert.crt:/usr/local/apache2/conf/server.crt:ro
      - ./services/apache/${APP_ENV}/conf/httpd-status.conf:/usr/local/apache2/conf/extra/httpd-status.conf:ro
      - web:/usr/local/apache2/htdocs
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail http://localhost:${WEB_HTTP_PORT:-80}/health?auto || exit 1",
        ]
      interval: 10s
      timeout: 10s
      retries: 10
    # depends_on:
    #   api:
    #     condition: service_healthy
    #   keycloak:
    #     condition: service_healthy
    platform: linux/amd64
    <<: *settings
