"""
This type stub file was generated by pyright.
"""

"""
Convenience wrapper that handles removing the request argument from the function
arguments if needed. As the actual function does not include the argument, it
would lead to a Python exception if the argument is not removed.

This wrapper will check if the function contains the request argument and if
not, will remove it from kwargs before calling the function.
"""
from typing import Callable, Any

def strip_request(func: Callable[..., Any]) -> Callable[..., Any]:
    """
    Wrapper that strips the request argument from kwargs
    """
    ...
