---
- name: DevContainer Ansible Taskfile Test
  hosts: localhost
  become: true
  tasks:
    - name: Ping localhost
      ansible.builtin.ping:

    - name: Show whoami
      ansible.builtin.command: whoami
      register: whoami_result
      changed_when: false

    - name: Print user
      ansible.builtin.debug:
        var: whoami_result.stdout
