"""
This type stub file was generated by pyright.
"""

from fastapi_keycloak_middleware.decorators.require_permission import require_permission
from fastapi_keycloak_middleware.decorators.strip_request import strip_request
from fastapi_keycloak_middleware.dependencies.check_permission import CheckPermissions
from fastapi_keycloak_middleware.dependencies.get_auth import get_auth
from fastapi_keycloak_middleware.dependencies.get_authorization_result import get_authorization_result
from fastapi_keycloak_middleware.dependencies.get_user import get_user
from fastapi_keycloak_middleware.fast_api_user import FastApiUser
from fastapi_keycloak_middleware.middleware import KeycloakMiddleware
from fastapi_keycloak_middleware.schemas.authorization_methods import AuthorizationMethod
from fastapi_keycloak_middleware.schemas.authorization_result import AuthorizationResult
from fastapi_keycloak_middleware.schemas.keycloak_configuration import KeycloakConfiguration
from fastapi_keycloak_middleware.schemas.match_strategy import MatchStrategy
from fastapi_keycloak_middleware.setup import setup_keycloak_middleware

"""
Middleware for FastAPI that supports authenticating users against Keycloak
"""
__version__ = ...
__all__ = [
	"AuthorizationResult",
	"KeycloakMiddleware",
	"KeycloakConfiguration",
	"AuthorizationMethod",
	"MatchStrategy",
	"FastApiUser",
	"CheckPermissions",
	"get_auth",
	"get_user",
	"get_authorization_result",
	"require_permission",
	"setup_keycloak_middleware",
	"strip_request",
]
